"""Claude API list prices, in US dollars per million tokens.

Prices change. This table is a snapshot, not a fact of nature -- check it
against the source below before you quote a number to anyone.

Source: https://platform.claude.com/docs/en/about-claude/models/overview.md
Checked: 5 September 2026
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict

PRICE_SOURCE = "https://platform.claude.com/docs/en/about-claude/models/overview.md"
PRICE_CHECKED = "2026-09-12"

#: Batch API requests are billed at half the synchronous price.
BATCH_DISCOUNT = 0.50

#: A prompt-cache read costs 10% of the base input price on opus-5, sonnet-5
#: and haiku-4.5. It is NOT uniform: on fable-5.1 a cache read is 2.5% of the
#: input price ($0.25/Mtok against $10.00/Mtok). Checked 2026-09-06.
CACHE_READ_FRACTION = {
    "fable-5.1": 0.025,
    "opus-5": 0.10,
    "sonnet-5": 0.10,
    "haiku-4.5": 0.10,
}


@dataclass(frozen=True)
class Model:
    """One model's list price and headline limits.

    Attributes:
        model_id: The exact string sent as ``model`` in an API request.
        input_per_mtok: US dollars per one million input tokens.
        output_per_mtok: US dollars per one million output tokens.
        context_tokens: Size of the context window, in tokens.
    """

    model_id: str
    input_per_mtok: float
    output_per_mtok: float
    context_tokens: int


MODELS: Dict[str, Model] = {
    "fable-5.1": Model("claude-fable-5-1", 10.00, 50.00, 1_000_000),
    "opus-5": Model("claude-opus-5", 5.00, 25.00, 1_000_000),
    "sonnet-5": Model("claude-sonnet-5", 2.00, 10.00, 1_000_000),
    "haiku-4.5": Model("claude-haiku-4-5", 1.00, 5.00, 200_000),
}

DEFAULT_MODEL = "opus-5"


def cost_usd(model_key: str, input_tokens: int, output_tokens: int) -> float:
    """Return the list-price cost of one request, in US dollars.

    Args:
        model_key: A key of :data:`MODELS`, e.g. ``"opus-5"``.
        input_tokens: Tokens sent, including the system prompt and any history.
        output_tokens: Tokens generated by the model.

    Returns:
        Cost in US dollars. No caching, no batch discount, no free tier.

    Raises:
        KeyError: If ``model_key`` is not in :data:`MODELS`.
    """
    model = MODELS[model_key]
    return (
        input_tokens * model.input_per_mtok
        + output_tokens * model.output_per_mtok
    ) / 1_000_000
